---
title: What can I do with the platform?
keywords: homepage
summary: These brief instructions will help you get started quickly with the platform
---

== Introduction
The secure open platform enables you to build interoperable apps for health and social care.

Our platform provides the plumbing and takes care of much of the "heavy lifting" allowing you to concentrate your efforts on application functionality while the platform deals with issues including interoperability, cyber-security, information governance and business continuity.

Unlike many other platforms which are based on proprietary approaches which mean your application is locked-in to the platform we use established open standards including openEHR, IHE-XDS, FHIR and SMART which means you applications are easily transportable to other platforms based on these standards.

To find out more about the rationale and concepts behind the open platform approach, you may want to look this video.

video::hrdLaWk-beQ[youtube, width=420]

== Create an Account
Your first step to using the platform is to create an account.
Tier 1 usage is free of charge and no credit card details are necessary to create an account.
To create your account just http://c4h.noesis.limited/#/register[click here].

== Build an Operino
The building blocks of the platform are called Operinos.
An Operino provides a container for a set of services from the platform that you need for a particular application to use the platform you need at least one Operino, although you can create as many as you need.

== Explore the API
All interaction with the platform is through a set of REST APIs that are provisioned for you when you create an Operino.
The easiest way to understand how these APIs work and the services they provide is to read the documentation and explore the APIs using Postman which provides a test harness allowing you to experiment with the APIs available in your Operinos.

== Connect you First Application
Once you understand the basics you will be ready to connect your first application to the platform.
You can build applications to run on the platform using virtually any web development language of your choice.
